[link text](https://)# Support Vector Regression (SVR)

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('DATA2.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[ 21]
 [ 25]
 [ 16]
 [  2]
 [ 11]
 [  0]
 [  0]
 [ 14]
 [ 16]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 38]
 [ 45]
 [  1]
 [  7]
 [  0]
 [  0]
 [  8]
 [  0]
 [ 32]
 [ 30]
 [ 11]
 [  4]
 [  0]
 [ 18]
 [ 40]
 [ 61]
 [ 19]
 [ 61]
 [ 53]
 [ 29]
 [ 10]
 [ 10]
 [ 10]
 [ 16]
 [ 19]
 [  4]
 [  5]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  1]
 [  2]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  3]
 [  0]
 [  0]
 [  0]
 [  0]
 [  4]
 [  0]
 [  0]
 [  0]
 [  0]
 [  1]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  1]
 [  4]
 [  9]
 [ 18]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 16]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 29]
 [ 32]
 [ 21]
 [ 42]
 [ 53]
 [ 10]
 [  1]
 [  0]
 [  0]
 [ 19]
 [ 29]
 [ 68]
 [ 79]
 [ 12]
 [  8]
 [  0]
 [  0]
 [ 17]
 [  0]
 [  0]
 [  4]
 [  0]
 [  7]
 [  0]
 [  0]
 [  0]
 [  0]
 [  0]
 [ 28]
 [ 42]
 [ 61]
 [ 17]
 [ 18]
 [ 38]
 [ 21]
 [ 22]
 [ 12]
 [  0]
 [  0]
 [  0]
 [  0]

In [ ]:
print(y)

[ 8070  8100  8080  1891  2918  1891  1891  3251  3298  2134  2415  2130
  2099  2132  1980  2100  1789  2409  2121  1903  1851  7660  9082  2291
  2009  2100  1897  1999  2109  5143  5143  2567  2134  1890  2987  7689
 10981  5721 10982  9867  6721  3890  3890  3890  3976  4132  2501  2143
  1890  1890  1891  1894  1890  1890  1890  1890  1898  1890  1890  1891
  1891  1892  1891  1891  1891  1891  1891  1891  1891  1891  1891  1891
  1891  1891  1891  1891  1891  1891  1891  1891  1891  1891  1891  1891
  1891  1891  1891  1891  1891  5231  1891  1891  1891  1891  1891  5132
  1891  1891  1891  1891  1891  1891  7612  8100  6599  8721  8821  2876
  1891  1891  1893  3288  4111  8123  7656  2789  2312  1891  1891  2798
  1891  1891  1891  1891  1891  1891  1891  1891  1891  1891  3467  7122
  9176  2898  3000  5122  3211  3265  2980  1891  1891  1890  1890  2765
  1890  1890  2989  3019  2999  1890  1890  2898  3122  1890  1890  1890
  1890  2456  2001  1890  1890  1890  1890  1890  2

In [ ]:
y = y.reshape(len(y),1)

In [ ]:
print(y)

[[ 8070]
 [ 8100]
 [ 8080]
 [ 1891]
 [ 2918]
 [ 1891]
 [ 1891]
 [ 3251]
 [ 3298]
 [ 2134]
 [ 2415]
 [ 2130]
 [ 2099]
 [ 2132]
 [ 1980]
 [ 2100]
 [ 1789]
 [ 2409]
 [ 2121]
 [ 1903]
 [ 1851]
 [ 7660]
 [ 9082]
 [ 2291]
 [ 2009]
 [ 2100]
 [ 1897]
 [ 1999]
 [ 2109]
 [ 5143]
 [ 5143]
 [ 2567]
 [ 2134]
 [ 1890]
 [ 2987]
 [ 7689]
 [10981]
 [ 5721]
 [10982]
 [ 9867]
 [ 6721]
 [ 3890]
 [ 3890]
 [ 3890]
 [ 3976]
 [ 4132]
 [ 2501]
 [ 2143]
 [ 1890]
 [ 1890]
 [ 1891]
 [ 1894]
 [ 1890]
 [ 1890]
 [ 1890]
 [ 1890]
 [ 1898]
 [ 1890]
 [ 1890]
 [ 1891]
 [ 1891]
 [ 1892]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 5231]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 5132]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 1891]
 [ 7612]
 [ 8100]
 [ 6599]
 [ 8721]
 [ 8821]
 [ 2876]
 [ 1891]
 [ 1891]
 [ 1893]
 

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [ ]:
print(X)

[[ 0.27283924]
 [ 0.43933292]
 [ 0.06472213]
 [-0.51800576]
 [-0.14339497]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.01852471]
 [ 0.06472213]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [ 0.98043739]
 [ 1.27180133]
 [-0.55962918]
 [-0.30988865]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.26826523]
 [-0.6012526 ]
 [ 0.73069686]
 [ 0.64745002]
 [-0.14339497]
 [-0.43475892]
 [-0.6012526 ]
 [ 0.14796897]
 [ 1.06368423]
 [ 1.93777606]
 [ 0.18959239]
 [ 1.93777606]
 [ 1.6047887 ]
 [ 0.6058266 ]
 [-0.18501839]
 [-0.18501839]
 [-0.18501839]
 [ 0.06472213]
 [ 0.18959239]
 [-0.43475892]
 [-0.39313549]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.55962918]
 [-0.51800576]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.6012526 ]
 [-0.47638234]
 [-0.60125

In [ ]:
print(y)

[[ 1.26991277]
 [ 1.27886019]
 [ 1.27289524]
 [-0.5729578 ]
 [-0.26665774]
 [-0.5729578 ]
 [-0.5729578 ]
 [-0.16734136]
 [-0.15332373]
 [-0.50048369]
 [-0.41667617]
 [-0.50167668]
 [-0.51092234]
 [-0.50108018]
 [-0.54641378]
 [-0.5106241 ]
 [-0.60337903]
 [-0.41846566]
 [-0.5043609 ]
 [-0.56937883]
 [-0.58488769]
 [ 1.14763134]
 [ 1.57173912]
 [-0.45365885]
 [-0.53776461]
 [-0.5106241 ]
 [-0.57116832]
 [-0.54074708]
 [-0.50793987]
 [ 0.39694268]
 [ 0.39694268]
 [-0.37134257]
 [-0.50048369]
 [-0.57325605]
 [-0.24607867]
 [ 1.15628051]
 [ 2.13811089]
 [ 0.56932967]
 [ 2.13840914]
 [ 1.80586331]
 [ 0.86757705]
 [ 0.02323871]
 [ 0.02323871]
 [ 0.02323871]
 [ 0.04888799]
 [ 0.09541458]
 [-0.3910269 ]
 [-0.49779946]
 [-0.57325605]
 [-0.57325605]
 [-0.5729578 ]
 [-0.57206306]
 [-0.57325605]
 [-0.57325605]
 [-0.57325605]
 [-0.57325605]
 [-0.57087007]
 [-0.57325605]
 [-0.57325605]
 [-0.5729578 ]
 [-0.5729578 ]
 [-0.57265955]
 [-0.5729578 ]
 [-0.5729578 ]
 [-0.5729578 ]
 [-0.5729578 ]
 [-0.57295

## Training the SVR model on the whole dataset

In [ ]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X, y)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

## Predicting a new result

In [19]:
sc_y.inverse_transform(regressor.predict(sc_X.transform([[80]])).reshape(-1,1))

array([[12923.94311356]])